# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00e49aedaa8421482ba852061de1e10bb6d8ef5d3de6228f910081572a3e8f7c8ae86f3f7dd877d1fbd8c393a0c2fa3c93a10033b55f2c32db1362b9e92cd6e1

test:
  secret_key_base: b14978249db1baf71fd38bcfa0f0a3c1c8640e82042f897cfe4168563f828554d595bb2cc466ab0509ce2aa0c42ca4547efe99b74762958a143717051e495e6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
